name       : perl-gtk2-appindicator
version    : 0.15
release    : 3
source     :
    - https://cpan.metacpan.org/authors/id/O/OE/OESTERHOL/Gtk2-AppIndicator-0.15.tar.gz : a25cb071e214fb89b4450aa4605031eae89b7961e149b0d6e8f491c19c14a90a
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Perl extension for libappindicator.
description: |
    Gtk2::AppIndicator - Perl extension for libappindicator.
builddeps  :
    - pkgconfig(appindicator3-0.1)
rundeps    :
    - perl-gtk2
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
